client_id = "a64d39b251fbf913292da4235c7c94f7"
name = "base-app"
application_url = "https://shopify-base-app.onrender.com"
embedded = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
uri = "/webhooks"
topics = ["app_subscriptions/update", "app/uninstalled", "shop/update"]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]

[access_scopes]
scopes = "read_products,write_products,read_customers,write_customers,read_orders,write_orders,read_content,write_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://shopify-base-app.onrender.com/auth/callback"
]